[package]
name = "nonogram-rs"
description = "A fast and lightwight nonogram solving library."
authors = ["Rico Riedel <rico.riedel@protonmail.ch>"]
version = "2.0.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/ricoriedel/nonogram-rs"