[package]
name = "nonogram-rs"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
serde = { version = "1.0.131", optional = true, features = ["derive"]}
serde_json = { version = "1.0.72", optional = true }
clap = { version = "3.0.0", optional = true }

[features]
json = ["serde", "serde_json"]
cmd = ["clap"]

[[bin]]
name = "nonosolver"
required-features = ["json", "cmd"]