# Don't forget to update:
# - main.rs
# - PKGBUILD

[package]
name = "nonogram-rs"
description = "A fast and simple nonogram solver."
authors = ["Rico Riedel <rico.riedel@protonmail.ch>"]
version = "1.1.1"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/ricoriedel/nonogram-rs"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"]}
serde_json = { version = "1.0", optional = true }
clap = { version = "3.1", optional = true, features = ["derive"] }

[[bin]]
name = "nonosolver"
required-features = ["clap", "serde", "serde_json"]