[package]
name = "nonogram-rs"
description = "A fast and lightweight library to solve nonograms."
version = "1.0.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/Someone357/nonogram-rs"

[dependencies]
serde = { version = "~1.0", optional = true, features = ["derive"]}
serde_json = { version = "~1.0", optional = true }
clap = { version = "~3.0", optional = true }

[features]
json = ["serde", "serde_json"]
cmd = ["clap"]

[[bin]]
name = "nonosolver"
required-features = ["json", "cmd"]