[package]
name = "nonogram-rs"
description = "A fast and lightweight library to solve nonograms."
version = "1.0.1"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/Someone357/nonogram-rs"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"]}
serde_json = { version = "1.0", optional = true }
clap = { version = "3.0", optional = true }

[[bin]]
name = "nonosolver"
required-features = ["clap", "serde", "serde_json"]